{
 "title": "GoFlow - Internals",
 "description": "Metrics about the NetFlow+sFlow collector",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NetFlows Total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "format": "pps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(flow_process_nf_flowset_records_sum[5m]))"
    }
   ]
  },
  {
   "title": "sFlows Total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "format": "pps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(flow_process_sf_samples_sum[5m]))"
    }
   ]
  },
  { "title": "Flows UDP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "UDP2Kafka Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(udp_traffic_bytes[5m])) by (remote_ip)",
     "legendFormat": "{{ remote_ip }}"
    },
    {
     "expr": "sum(rate(udp_traffic_bytes[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "UDP2Kafka packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(udp_traffic_packets[5m])) by (remote_ip)",
     "legendFormat": "{{ remote_ip }}"
    },
    {
     "expr": "sum(rate(udp_traffic_packets[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "sFlow UDP Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_traffic_bytes{type=\"sFlow\"}[5m])) by (remote_ip)",
     "legendFormat": "{{ remote_ip }}"
    },
    {
     "aggregator": "sum",
     "alias": "$tag_type | Total",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(rate(flow_traffic_bytes{type=\"sFlow\"}[5m]))",
     "legendFormat": "sFlow | Total",
     "tags": { "type": "sFlow" }
    }
   ]
  },
  {
   "title": "sFlow UDP Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_traffic_packets{type=\"sFlow\"}[5m])) by (remote_ip)",
     "legendFormat": "{{ remote_ip }}"
    },
    {
     "aggregator": "sum",
     "alias": "$tag_type | Total",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(rate(flow_traffic_packets{type=\"sFlow\"}[5m]))",
     "legendFormat": "sFlow | Total",
     "tags": { "type": "sFlow" }
    }
   ]
  },
  {
   "title": "NetFlow UDP Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_traffic_bytes{type=\"NetFlow\"}[1m])) by (remote_ip)",
     "legendFormat": "{{ remote_ip }}"
    },
    {
     "expr": "sum(rate(flow_traffic_bytes{type=\"NetFlow\"}[1m]))",
     "legendFormat": "NetFlow | Total"
    }
   ]
  },
  {
   "title": "NetFlow UDP Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_traffic_packets{type=\"NetFlow\"}[5m])) by (remote_ip)",
     "legendFormat": "{{ remote_ip }}"
    },
    {
     "aggregator": "sum",
     "alias": "$tag_type | Total",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(rate(flow_traffic_packets{type=\"NetFlow\"}[5m]))",
     "legendFormat": "NetFlow | Total",
     "tags": { "type": "NetFlow" }
    }
   ]
  },
  { "title": "NetFlow metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "NetFlows by type and version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_process_nf_flowset_records_sum[5m])) by (version,type)",
     "legendFormat": "{{ version }} | {{ type }} "
    }
   ]
  },
  {
   "title": "NetFlows errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_process_nf_errors_count[5m])) by (error)",
     "legendFormat": "{{ error }}"
    }
   ]
  },
  {
   "title": "NetFlow templates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_process_nf_templates_count[5m])) by (version,router,type)",
     "legendFormat": "{{ version }} | {{ router }} | {{ type }}"
    }
   ]
  },
  {
   "title": "NetFlows - DataFlowSets by router and version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_process_nf_flowset_records_sum[5m])) by (router,version)",
     "legendFormat": "{{ router }} | {{ version }}"
    }
   ]
  },
  {
   "title": "Time between flow and processing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_process_nf_delay_summary_seconds[5m])) by (quantile,router,version)",
     "legendFormat": "Q{{ quantile }} | {{ router }} | {{ version }}"
    }
   ]
  },
  { "title": "sFlow metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "sFlows by type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_process_sf_samples_sum[5m])) by (version,type)",
     "legendFormat": "{{ version }} | {{ type }}"
    }
   ]
  },
  {
   "title": "sFlows Flow records by agent and version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_process_sf_samples_records_sum{type=\"FlowSample\"}[5m])) by (agent,version)",
     "legendFormat": "{{ agent }} | {{ version }}"
    }
   ]
  },
  { "title": "NetFlow decoder metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "NetFlow decoding time quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(flow_summary_decoding_time_us{name=\"NetFlow\"}) by (quantile)",
     "legendFormat": "Q{{ quantile }}"
    }
   ]
  },
  {
   "title": "NetFlow processing time quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(flow_summary_processing_time_us{name=\"NetFlow\"}) by (quantile)",
     "legendFormat": "Q{{ quantile }}"
    }
   ]
  },
  {
   "title": "NetFlow worker rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_decoder_count{name=\"NetFlow\"}[5m])) by (worker)",
     "legendFormat": "Worker {{ worker }}"
    }
   ]
  },
  { "title": "sFlow decoder metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "sFlow decoding time quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(flow_summary_decoding_time_us{name=\"sFlow\"}) by (quantile)",
     "legendFormat": "Q{{ quantile }}"
    }
   ]
  },
  {
   "title": "sFlow processing time quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(flow_summary_decoding_time_us{name=\"sFlow\"}) by (quantile)",
     "legendFormat": "Q{{ quantile }}"
    }
   ]
  },
  {
   "title": "sFlow worker rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_decoder_count{name=\"sFlow\"}[5m])) by (worker)",
     "legendFormat": "Worker {{ worker }}"
    }
   ]
  }
 ]
}