global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'consumer'
    static_configs:
    - targets:
      - consumer:8080
    metrics_path: /metrics
  - job_name: 'flowdata'
    static_configs:
    - targets:
      - consumer:8080
    metrics_path: /flowdata
