{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "peer", "label": "Peers", "query": "label_values(flow_bits, peer)" },
   {
    "name": "remoteas",
    "label": "Remote Network",
    "query": "label_values(flow_bits, remoteas)"
   },
   {
    "name": "direction",
    "label": "Direction",
    "query": "label_values(flow_bits, direction)"
   },
   {
    "name": "ipversion",
    "label": "IP Version",
    "query": "label_values(flow_bits, ipversion)"
   },
   {
    "name": "protoname",
    "label": "Protocol",
    "query": "label_values(flow_bits, protoname)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(flow_bits, application)"
   },
   {
    "name": "router",
    "label": "Router",
    "query": "label_values(flow_bits, router)"
   },
   {
    "name": "remotecountry",
    "label": "Geolocation",
    "query": "label_values(flow_bits, remotecountry)"
   }
  ]
 },
 "panels": [
  {
   "title": "Remote Countries",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (remotecountry) (rate(flow_bits{peer=~\"$peer\",direction=~\"$direction\",ipversion=~\"$ipversion\",protoname=~\"$protoname\",application=~\"$application\", router=~\"$router\", remoteas=~\"$remoteas\"}[1m]))",
     "legendFormat": "{{ remotecountry }}"
    }
   ]
  },
  {
   "title": "Up- and Download",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (direction) (rate(flow_bits{peer=~\"$peer\",direction=~\"$direction\",ipversion=~\"$ipversion\",protoname=~\"$protoname\",application=~\"$application\", router=~\"$router\", remoteas=~\"$remoteas\", remotecountry=~\"$remotecountry\"}[1m]))",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Traffic by IP Version",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (ipversion) (rate(flow_bits{peer=~\"$peer\",direction=~\"$direction\",ipversion=~\"$ipversion\",protoname=~\"$protoname\",application=~\"$application\", router=~\"$router\", remoteas=~\"$remoteas\", remotecountry=~\"$remotecountry\"}[1m]))",
     "legendFormat": "{{ ipversion }}"
    }
   ]
  },
  {
   "title": "Traffic by Protocol",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (protoname) (rate(flow_bits{peer=~\"$peer\",direction=~\"$direction\",ipversion=~\"$ipversion\",protoname=~\"$protoname\",application=~\"$application\", router=~\"$router\", remoteas=~\"$remoteas\", remotecountry=~\"$remotecountry\"}[1m]))",
     "legendFormat": "{{ protoname }}"
    }
   ]
  },
  {
   "title": "Traffic by Application",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (application) (rate(flow_bits{peer=~\"$peer\",direction=~\"$direction\",ipversion=~\"$ipversion\",protoname=~\"$protoname\",application=~\"$application\", router=~\"$router\", remoteas=~\"$remoteas\", remotecountry=~\"$remotecountry\"}[1m]))",
     "legendFormat": "{{ application }}"
    }
   ]
  },
  {
   "title": "Traffic by Router",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (router) (rate(flow_bits{peer=~\"$peer\",direction=~\"$direction\",ipversion=~\"$ipversion\",protoname=~\"$protoname\",application=~\"$application\", router=~\"$router\", remoteas=~\"$remoteas\", remotecountry=~\"$remotecountry\"}[1m]))",
     "legendFormat": "{{ router }}"
    }
   ]
  }
 ]
}